### ISSUE TITLE
Compiling harfbuzz reports an error

### ISSUE THREAD

**Issue by 12qwetyd** [Dongdongshe/K-Scheduler#15]
Hi, I'm using afl_integration/build_example to compile harfbuzz with the following error when it comes to make statement, can you give me some suggestions to solve the problem?
![image](https://user-images.githubusercontent.com/51839458/231095159-618b3d6b-f30c-4b5c-a355-dc87f4abaa69.png)

make: Entering directory '/home/canicula/K-Scheduler/afl_integration/build_example/BUILD/src'
  GEN      libharfbuzz-fuzzing.la
libtool:   error: cannot build libtool library 'libharfbuzz-fuzzing.la' from non-libtool objects on this host: /home/canicula/K-Scheduler/afl_integration/build_example/afl-llvm-rt.o
make: *** [Makefile:1542: libharfbuzz-fuzzing.la] Error 1
make: Leaving directory '/home/canicula/K-Scheduler/afl_integration/build_example/BUILD/src'

**Comment by Dongdongshe** [comment]
Unfortunately, I can't reproduce your error on my end. Could you double-check if you followed the tutorial correctly? 

Here are some tips for debugging your error: from the error message, it seemed the error was caused by LDFLAGS=/PATH/TO/afl-llvm-rt.o. **This LDFLAGS is only used at the last step to build harfbuzz_afl_asan.** Hence, you can safely unset it by using this command ($unset LDFLAGS), then build the harfbuzz library. Then re-set LDFLAGS before the last step of building. 

Let me know if you still encounter any issues. I am happy to help.

**Comment by 12qwetyd** [comment]
I just started compiling on ubuntu22 and followed the build_example steps to the letter, and I always got the above error, then I pulled the code again and executed it on ubuntu20, and the error stopped appearing, so I suspect it might be a ubuntu version problem here?Thank you!
