### ISSUE TITLE
Some problems with afl integration

### ISSUE THREAD

**Issue by MandaCai** [Dongdongshe/K-Scheduler#16]
Hello, I have tested and read some K-Scheduler implementation source codes, and I have some questions to ask
1. During the experiment, it was found that the execution speed of using afl-fuzz_kscheduler is generally slower than that of using afl-fuzz. In the edge_log file, it is found that the graph centrality is calculated every 6 minutes on average. Where could the discrepancy be when there is no calculation
2. I don't know much about the instrumentation method of -fsanitize-coverage=trace-pc-guard. The default should be edge coverage.Cur_coverage should store edge coverage information, but these edge information are directly used in gen_dyn_weight.py to delete covered nodes. I would like to ask about the specific implementation here.

<img width="447" alt="image" src="https://github.com/Dongdongshe/K-Scheduler/assets/62645711/b2f3a212-1f1e-462a-a97f-7526b33d7591">

<img width="431" alt="image" src="https://github.com/Dongdongshe/K-Scheduler/assets/62645711/c48eef7d-c3dc-4c63-94d1-52ec1ed09a4b">

**Comment by Dongdongshe** [comment]
Hi Manda,

Thanks for your interest in K-Scheduler!
1. K-Scheduler would incur slight runtime overhead due to the graph centrality analysis, but our evaluation results show that the drop in fuzzing throughput would not affect fuzzing performance. What do you mean by "discrepancy when there is no calculation"? 
2. Regarding llvm sanitizer coverage, please look at the official llvm documents https://clang.llvm.org/docs/SanitizerCoverage.html. In short, llvm sanitizer coverage is collision-free instrumentation widely used in fuzzers (e.g., AFL++'s default instrumentation is an inline version of llvm sanitizer **edge coverage with the pruning feature**). In K-Scheduler, we use the default setting of llvm sanitizer **edge coverage without the pruning feature**. I am guessing you were asking, since we are instrumenting the **edge** (the C code snippet in your post), why can we delete **nodes** (the Python code snippet in your post)? 

The short answer is that **"edge coverage without prune feature" = "node coverage" + "critical edge coverage"** (Please see the definition of prune feature and critical edge in https://clang.llvm.org/docs/SanitizerCoverage.html). I will use the same example from llvm sanitizer coverage to explain how it works as follows:
Code:
```
void foo(int *a) {
  if (a)
    *a = 0;
}
```
It contains three basic blocks, let’s name them A, B, C. If we do node instrumentation, we can have three nodes (each node corresponds to a basic block)
```
A -> node coverage 
|\
| \
|  B -> node coverage 
| /
|/
C -> node coverage 
```
But such node coverage is coarse-grained and fails to detect certain edges(A->C). Please read llvm sanitizer coverage document for more details. That's what we call critical edge. To solve this problem, edge coverage would add an explicit node to catch the critical edge shown as node D as follows:
```
A
|\
| \
D  B     (A,B,C -> node coverage; D -> critical edge coverage )
| /
|/
C

```
For this code example, K-Scheduler uses llvm sanitizer edge coverage without the pruning to instrument four locations (A, B, C, and D nodes). Therefore, we can literally delete nodes on an "edge coverage graph". Let me know if you have any questions.

Best,
Dongdong

**Comment by MandaCai** [comment]
Can it be understood in this way？ this edge coverage is not the edge identifier calculated by the two basic block identifiers in llvmmode in afl. through the introduction of virtual nodes, as long as normal nodes and virtual nodes are covered, it can be considered as covering all edges. Indirect calculation of edge coverage by node coverage

**Comment by Dongdongshe** [comment]
Yes, exactly.

**Comment by MandaCai** [comment]
Thank you very much for your prompt reply
